batch index: implement MarshalText and UnmarshalText
samsarahq/thunder pull request #453
Opened 2021-03-15 21:16 UTC by yolandaz

currently, json.Marshal on batch.Index throws an error `json: unsupported type: map[batch.Index]bool` when attempting to run. This change fixes that issue by implementing MarshalText and UnmarshalText on batch.Index

2021-03-15 21:27 UTC, steveshi7 approved these changes

2021-03-15 21:27 UTC, steveshi7 commented on batch/index.go
> +	return json.Marshal(index(s))
what is `s` referring to here

2021-03-15 21:38 UTC, steveshi7 requested changes
sorry, accidentally pressed approve

2021-03-15 22:17 UTC, yolandaz commented on batch/index.go
> +	return json.Marshal(index(s))
oops should be i

2021-03-16 22:11 UTC, steveshi7 approved these changes
lgtm

2021-03-16 22:22 UTC, closed without merging